// lib/data/hospitals_data.dart

final List<Map<String, dynamic>> hospitalsData = [
  {
    "id": "h1",
    "name": "Amandeep Hospital",
    "type": "Hospital",
    "address": "Model Town, Rani Ka Bagh, Amritsar, Punjab 143001",
    "contact_number": "+91 9876543210",
    "email": "info@amandeephospital.in",
    "photo_url": "https://images.unsplash.com/photo-1584433144859-1fc3ab64a957",
    "cover_image":
        "https://images.unsplash.com/photo-1576765607924-bf1b44f2d1f0",
    "description":
        "A multispecialty hospital offering orthopedic, cardiac, and emergency care.",
    "rating": 4.7,
    "is_verified": true,
    "facilities": ["24x7 Emergency", "ICU", "Pharmacy", "Laboratory"],
    "specialties": ["Orthopedics", "Cardiology", "Neurology"],
    "doctors": [
      {
        "id": "d1",
        "name": "Dr. Manpreet Singh",
        "specialization": "Orthopedic Surgeon",
        "qualification": "MBBS, MS (Ortho)",
        "experience": "12 years",
        "gender": "Male",
        "photo_url": "https://randomuser.me/api/portraits/men/42.jpg",
        "about":
            "Specialist in bone and joint surgeries with over 1000 successful operations.",
        "hospital_id": "h1",
        "hospital_name": "Amandeep Hospital",
        "consultation_fee": 800,
        "online_consultation": true,
        "home_visit": false,
        "available_days": ["Mon", "Wed", "Fri"],
        "available_from": "10:00 AM",
        "available_to": "4:00 PM",
        "rating": 4.8,
        "total_reviews": 120,
        "is_active": true,
      },
      {
        "id": "d2",
        "name": "Dr. Simran Kaur",
        "specialization": "Cardiologist",
        "qualification": "MBBS, MD (Cardiology)",
        "experience": "9 years",
        "gender": "Female",
        "photo_url": "https://randomuser.me/api/portraits/women/45.jpg",
        "about": "Expert in heart diseases and preventive cardiology.",
        "hospital_id": "h1",
        "hospital_name": "Amandeep Hospital",
        "consultation_fee": 1000,
        "online_consultation": true,
        "home_visit": false,
        "available_days": ["Tue", "Thu", "Sat"],
        "available_from": "11:00 AM",
        "available_to": "5:00 PM",
        "rating": 4.9,
        "total_reviews": 98,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h2",
    "name": "Apollo Clinic",
    "type": "Clinic",
    "address": "Lawrence Road, Amritsar, Punjab 143001",
    "contact_number": "+91 9812345678",
    "email": "support@apolloclinic.in",
    "photo_url": "https://images.unsplash.com/photo-1576765607924-bf1b44f2d1f0",
    "cover_image":
        "https://images.unsplash.com/photo-1606813902919-9424d1bda3c8",
    "description": "Comprehensive diagnostic and consultation clinic.",
    "rating": 4.5,
    "is_verified": true,
    "facilities": ["Pathology Lab", "Diagnostics", "Pharmacy"],
    "specialties": ["General Medicine", "Dermatology", "ENT"],
    "doctors": [
      {
        "id": "d3",
        "name": "Dr. Rajesh Sharma",
        "specialization": "General Physician",
        "qualification": "MBBS, MD (Medicine)",
        "experience": "15 years",
        "gender": "Male",
        "photo_url": "https://randomuser.me/api/portraits/men/48.jpg",
        "about":
            "Experienced family doctor specializing in lifestyle diseases.",
        "hospital_id": "h2",
        "hospital_name": "Apollo Clinic",
        "consultation_fee": 600,
        "online_consultation": true,
        "home_visit": true,
        "available_days": ["Mon", "Tue", "Thu", "Fri"],
        "available_from": "9:30 AM",
        "available_to": "2:00 PM",
        "rating": 4.7,
        "total_reviews": 200,
        "is_active": true,
      },
      {
        "id": "d4",
        "name": "Dr. Neha Arora",
        "specialization": "Dermatologist",
        "qualification": "MBBS, MD (Skin & VD)",
        "experience": "8 years",
        "gender": "Female",
        "photo_url": "https://randomuser.me/api/portraits/women/47.jpg",
        "about": "Expert in skincare, acne, and laser treatments.",
        "hospital_id": "h2",
        "hospital_name": "Apollo Clinic",
        "consultation_fee": 700,
        "online_consultation": true,
        "home_visit": false,
        "available_days": ["Wed", "Fri", "Sat"],
        "available_from": "11:00 AM",
        "available_to": "4:00 PM",
        "rating": 4.8,
        "total_reviews": 135,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h3",
    "name": "Fortis Escorts Hospital",
    "type": "Hospital",
    "address": "Majitha-Verka Bypass Road, Amritsar, Punjab 143001",
    "contact_number": "+91 9643212345",
    "email": "contact@fortisamritsar.com",
    "photo_url": "https://images.unsplash.com/photo-1606813902973-6c9cf0b6b870",
    "cover_image":
        "https://images.unsplash.com/photo-1580281658629-889c96d1f9a2",
    "description":
        "Super specialty hospital with cardiac, oncology, and ortho care.",
    "rating": 4.8,
    "is_verified": true,
    "facilities": ["ICU", "Cardiac Center", "24x7 Ambulance"],
    "specialties": ["Cardiology", "Oncology", "Orthopedics"],
    "doctors": [
      {
        "id": "d5",
        "name": "Dr. Ritu Kapoor",
        "specialization": "Cardiac Surgeon",
        "qualification": "MBBS, MCh (Cardiac Surgery)",
        "experience": "14 years",
        "gender": "Female",
        "photo_url": "https://randomuser.me/api/portraits/women/52.jpg",
        "about": "Renowned cardiac surgeon specializing in bypass surgeries.",
        "hospital_id": "h3",
        "hospital_name": "Fortis Escorts Hospital",
        "consultation_fee": 1500,
        "online_consultation": true,
        "home_visit": false,
        "available_days": ["Tue", "Thu", "Sat"],
        "available_from": "9:00 AM",
        "available_to": "3:00 PM",
        "rating": 4.9,
        "total_reviews": 250,
        "is_active": true,
      },
      {
        "id": "d6",
        "name": "Dr. Ankit Mehra",
        "specialization": "Oncologist",
        "qualification": "MBBS, DM (Oncology)",
        "experience": "10 years",
        "gender": "Male",
        "photo_url": "https://randomuser.me/api/portraits/men/53.jpg",
        "about": "Specialist in radiation and chemotherapy treatments.",
        "hospital_id": "h3",
        "hospital_name": "Fortis Escorts Hospital",
        "consultation_fee": 1200,
        "online_consultation": false,
        "home_visit": false,
        "available_days": ["Mon", "Wed", "Fri"],
        "available_from": "10:30 AM",
        "available_to": "5:00 PM",
        "rating": 4.9,
        "total_reviews": 180,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h4",
    "name": "Smile Dental Studio",
    "type": "Clinic",
    "address": "Mall Road, Amritsar, Punjab 143001",
    "contact_number": "+91 9988223344",
    "email": "smile@dentalstudio.in",
    "photo_url": "https://images.unsplash.com/photo-1606813902973-6c9cf0b6b870",
    "cover_image":
        "https://images.unsplash.com/photo-1595433707802-44e06b36e8e2",
    "description": "Dental clinic for cosmetic and general dentistry.",
    "rating": 4.9,
    "is_verified": true,
    "facilities": ["X-Ray", "Laser Dentistry", "Teeth Whitening"],
    "specialties": ["Dentistry", "Cosmetic Surgery"],
    "doctors": [
      {
        "id": "d7",
        "name": "Dr. Arjun Bedi",
        "specialization": "Dental Surgeon",
        "qualification": "BDS, MDS (Oral Surgery)",
        "experience": "7 years",
        "gender": "Male",
        "photo_url": "https://randomuser.me/api/portraits/men/65.jpg",
        "about": "Expert in root canals and smile makeovers.",
        "hospital_id": "h4",
        "hospital_name": "Smile Dental Studio",
        "consultation_fee": 500,
        "online_consultation": true,
        "home_visit": false,
        "available_days": ["Mon", "Tue", "Thu", "Sat"],
        "available_from": "10:00 AM",
        "available_to": "6:00 PM",
        "rating": 4.8,
        "total_reviews": 90,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h5",
    "name": "Sukhmani Hospital",
    "type": "Hospital",
    "address": "Green Avenue, Amritsar, Punjab 143001",
    "contact_number": "+91 9087654321",
    "email": "admin@sukhmanihospital.in",
    "photo_url": "https://images.unsplash.com/photo-1629909613654-28c1e53e5f6b",
    "cover_image":
        "https://images.unsplash.com/photo-1606813902919-9424d1bda3c8",
    "description":
        "Affordable general hospital focusing on gynecology and pediatrics.",
    "rating": 4.4,
    "is_verified": true,
    "facilities": ["Maternity Ward", "Pediatric ICU", "Pharmacy"],
    "specialties": ["Gynecology", "Pediatrics"],
    "doctors": [
      {
        "id": "d8",
        "name": "Dr. Priya Malhotra",
        "specialization": "Gynecologist",
        "qualification": "MBBS, MD (Gynecology)",
        "experience": "11 years",
        "gender": "Female",
        "photo_url": "https://randomuser.me/api/portraits/women/60.jpg",
        "about": "Specialist in maternal and women's health care.",
        "hospital_id": "h5",
        "hospital_name": "Sukhmani Hospital",
        "consultation_fee": 700,
        "online_consultation": true,
        "home_visit": false,
        "available_days": ["Mon", "Wed", "Fri"],
        "available_from": "10:00 AM",
        "available_to": "3:00 PM",
        "rating": 4.7,
        "total_reviews": 85,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h6",
    "name": "Ivy Hospital",
    "type": "Hospital",
    "address": "Airport Road, Amritsar, Punjab 143001",
    "contact_number": "+91 9123456789",
    "email": "info.amritsar@ivyhospital.com",
    "photo_url": "https://images.unsplash.com/photo-1551192070-51358a91b427",
    "cover_image":
        "https://images.unsplash.com/photo-1586773860414-72476c28d447",
    "description":
        "A leading tertiary care hospital with advanced medical facilities.",
    "rating": 4.6,
    "is_verified": true,
    "facilities": ["Advanced Diagnostics", "Modular OT", "Blood Bank"],
    "specialties": ["Gastroenterology", "Urology", "Nephrology"],
    "doctors": [
      {
        "id": "d9",
        "name": "Dr. Vikram Ahuja",
        "specialization": "Gastroenterologist",
        "qualification": "MBBS, DM (Gastroenterology)",
        "experience": "13 years",
        "gender": "Male",
        "photo_url": "https://randomuser.me/api/portraits/men/68.jpg",
        "about": "Expert in digestive disorders and endoscopic procedures.",
        "hospital_id": "h6",
        "hospital_name": "Ivy Hospital",
        "consultation_fee": 1100,
        "online_consultation": true,
        "home_visit": false,
        "available_days": ["Tue", "Thu", "Sat"],
        "available_from": "10:00 AM",
        "available_to": "4:00 PM",
        "rating": 4.8,
        "total_reviews": 150,
        "is_active": true,
      },
      {
        "id": "d10",
        "name": "Dr. Sonia Gupta",
        "specialization": "Nephrologist",
        "qualification": "MBBS, DM (Nephrology)",
        "experience": "10 years",
        "gender": "Female",
        "photo_url": "https://randomuser.me/api/portraits/women/69.jpg",
        "about": "Specializing in kidney diseases and dialysis.",
        "hospital_id": "h6",
        "hospital_name": "Ivy Hospital",
        "consultation_fee": 1200,
        "online_consultation": false,
        "home_visit": false,
        "available_days": ["Mon", "Wed", "Fri"],
        "available_from": "12:00 PM",
        "available_to": "5:00 PM",
        "rating": 4.7,
        "total_reviews": 110,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h7",
    "name": "Dr. Daljit Singh Eye Hospital",
    "type": "Hospital",
    "address": "The Mall, Amritsar Cantt, Amritsar, Punjab 143001",
    "contact_number": "+91 9876501234",
    "email": "contact@daljiteye.in",
    "photo_url": "https://images.unsplash.com/photo-1594951942368-757849e70e3c",
    "cover_image":
        "https://images.unsplash.com/photo-1628348068343-913b8417c805",
    "description":
        "A premier eye care center offering a wide range of ophthalmic services.",
    "rating": 4.9,
    "is_verified": true,
    "facilities": ["LASIK Surgery", "Retina Clinic", "Optical Store"],
    "specialties": ["Ophthalmology", "Optometry"],
    "doctors": [
      {
        "id": "d11",
        "name": "Dr. Harpreet Gill",
        "specialization": "Ophthalmologist",
        "qualification": "MBBS, MS (Ophthalmology)",
        "experience": "18 years",
        "gender": "Female",
        "photo_url": "https://randomuser.me/api/portraits/women/71.jpg",
        "about": "Specialist in cataract and refractive surgeries.",
        "hospital_id": "h7",
        "hospital_name": "Dr. Daljit Singh Eye Hospital",
        "consultation_fee": 900,
        "online_consultation": true,
        "home_visit": false,
        "available_days": ["Mon", "Tue", "Wed", "Thu", "Fri"],
        "available_from": "9:00 AM",
        "available_to": "5:00 PM",
        "rating": 4.9,
        "total_reviews": 300,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h8",
    "name": "Guru Nanak Dev Hospital",
    "type": "Hospital",
    "address": "Majitha Road, Amritsar, Punjab 143001",
    "contact_number": "+91 1832587453",
    "email": "info@gndhospital.gov.in",
    "photo_url": "https://images.unsplash.com/photo-1612740411033-c4b2ad35a298",
    "cover_image": "https://images.unsplash.com/photo-1562911791-c9a9415893a4",
    "description":
        "Government medical college and hospital providing subsidized healthcare.",
    "rating": 4.2,
    "is_verified": false,
    "facilities": ["Emergency Ward", "Surgical Units", "Radiology"],
    "specialties": ["General Surgery", "Internal Medicine", "ENT"],
    "doctors": [
      {
        "id": "d12",
        "name": "Dr. Jaswinder Singh",
        "specialization": "General Surgeon",
        "qualification": "MBBS, MS (General Surgery)",
        "experience": "20 years",
        "gender": "Male",
        "photo_url": "https://randomuser.me/api/portraits/men/75.jpg",
        "about":
            "Head of Surgery Department, specializing in complex procedures.",
        "hospital_id": "h8",
        "hospital_name": "Guru Nanak Dev Hospital",
        "consultation_fee": 300,
        "online_consultation": false,
        "home_visit": false,
        "available_days": ["Mon", "Wed", "Fri"],
        "available_from": "9:00 AM",
        "available_to": "1:00 PM",
        "rating": 4.5,
        "total_reviews": 450,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h9",
    "name": "Care & Cure Physiotherapy Clinic",
    "type": "Clinic",
    "address": "Ranjit Avenue, Amritsar, Punjab 143001",
    "contact_number": "+91 9911223344",
    "email": "careandcure@physio.com",
    "photo_url": "https://images.unsplash.com/photo-1581092580433-c1c543666a30",
    "cover_image":
        "https://images.unsplash.com/photo-1581092921394-1a3b137c35a8",
    "description":
        "Specialized clinic for physical therapy and sports injury rehabilitation.",
    "rating": 4.8,
    "is_verified": true,
    "facilities": ["Electrotherapy", "Exercise Therapy", "Sports Rehab"],
    "specialties": ["Physiotherapy"],
    "doctors": [
      {
        "id": "d13",
        "name": "Dr. Gurleen Saini",
        "specialization": "Physiotherapist",
        "qualification": "BPT, MPT (Ortho)",
        "experience": "6 years",
        "gender": "Female",
        "photo_url": "https://randomuser.me/api/portraits/women/78.jpg",
        "about": "Expert in post-operative rehabilitation and pain management.",
        "hospital_id": "h9",
        "hospital_name": "Care & Cure Physiotherapy Clinic",
        "consultation_fee": 600,
        "online_consultation": true,
        "home_visit": true,
        "available_days": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        "available_from": "10:00 AM",
        "available_to": "7:00 PM",
        "rating": 4.9,
        "total_reviews": 75,
        "is_active": true,
      },
    ],
  },
  {
    "id": "h10",
    "name": "Little Angels Children's Clinic",
    "type": "Clinic",
    "address": "Basant Avenue, Amritsar, Punjab 143001",
    "contact_number": "+91 9778899001",
    "email": "littleangels@clinic.in",
    "photo_url": "https://images.unsplash.com/photo-1599045118108-bf72f37c35e4",
    "cover_image":
        "https://images.unsplash.com/photo-1616161479214-a5518b565259",
    "description":
        "A dedicated pediatric clinic for child wellness and vaccinations.",
    "rating": 4.9,
    "is_verified": true,
    "facilities": ["Vaccination Center", "Growth Monitoring", "Nebulization"],
    "specialties": ["Pediatrics"],
    "doctors": [
      {
        "id": "d14",
        "name": "Dr. Rohit Verma",
        "specialization": "Pediatrician",
        "qualification": "MBBS, MD (Pediatrics)",
        "experience": "10 years",
        "gender": "Male",
        "photo_url": "https://randomuser.me/api/portraits/men/82.jpg",
        "about": "Passionate about child healthcare and development.",
        "hospital_id": "h10",
        "hospital_name": "Little Angels Children's Clinic",
        "consultation_fee": 700,
        "online_consultation": true,
        "home_visit": true,
        "available_days": ["Mon", "Wed", "Fri", "Sat"],
        "available_from": "11:00 AM",
        "available_to": "6:00 PM",
        "rating": 4.9,
        "total_reviews": 115,
        "is_active": true,
      },
    ],
  },
];
